#pragma once

const uint8_t default_lookup_table[64] = {
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x00,       /* Key shift thisthisststhisthstihst*/
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x00,       /* Key shift */
    0x2A,        /* Key delete */
    0x04,       /* Key a */
    0x05,       /* Key b */
    0x06,       /* Key c */
    0x07,       /* Key d */
    0x00,       /* Key shift */
    0x2A        /* Key delete */
};